# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda using `infix`"} # 1 hint
- ignore: {name: "Move brackets to avoid $"} # 1 hint
- ignore: {name: "Redundant $!"} # 3 hints
- ignore: {name: "Redundant <$>"} # 1 hint
- ignore: {name: "Redundant bracket"} # 2 hints
- ignore: {name: "Redundant return"} # 1 hint
- ignore: {name: "Unused LANGUAGE pragma"} # 5 hints
- ignore: {name: "Use const"} # 4 hints
- ignore: {name: "Use fmap"} # 3 hints
- ignore: {name: "Use fold"} # 1 hint
- ignore: {name: "Use newtype instead of data"} # 1 hint