name: PROJECTNAME
version: 0.1.0.0
github: GITHUB
license: BSD3
author: AUTHOR
maintainer: MAINTAINER
copyright: COPYRIGHT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: DESCRIPTION

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  PROJECTNAME-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
    - PROJECTNAME
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  PROJECTNAME-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - PROJECTNAME
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
