name:        rio-orphans
version:     0.1.0.0
synopsis:    Orphan instances for the RIO type in the rio package
description: See README and Haddocks at <https://www.stackage.org/package/rio-orphans>
license:     MIT
author:      Michael Snoyman
maintainer:  michael@snoyman.com
github:      commercialhaskell/rio
category:    Control

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.9 && < 10
- exceptions
- resourcet
- rio
- monad-control
- transformers-base

library:
  source-dirs: src

tests:
  rio-orphans-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rio-orphans
    - hspec
