name: Tests

on:
  pull_request:
  push:
      branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        snapshot:
        - nightly # GHC 9.12.2
        - lts-24 # GHC 9.10.2
        - lts-23 # GHC 9.8.4
        - lts-22 # GHC 9.6.7

    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Cache dependencies on Unix-like OS
        if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
        uses: actions/cache@v4
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.snapshot }}
      - name: Cache dependencies on Windows
        if: startsWith(runner.os, 'Windows')
        uses: actions/cache@v4
        with:
          path: |
             ~\AppData\Roaming\stack
             ~\AppData\Local\Programs\stack
          key: ${{ runner.os }}-${{ runner.arch }}-${{ matrix.snapshot }}
      - name: Build and run tests
        shell: bash
        run: |
            set -ex

            if [[ "${{ matrix.os }}" == "macos-13" || "${{ matrix.os }}" == "macos-latest" ]]
            then
              # macos-13 and macos-latest do not include Haskell tools as at 2025-09-14.
              curl -sSL https://get.haskellstack.org/ | sh
            fi

            stack --version
            stack test --fast --no-terminal --snapshot=${{ matrix.snapshot }}
